.PHONY: all

all: TestParser

TestParser:
	ghc --make haskell/TestChapel.hs haskell/ErrM.hs haskell/lexer.hs haskell/parser.hs haskell/AbsChapel.hs haskell/SkelChapel.hs haskell/PrintChapel.hs -o TestParser